// <auto-generated />
namespace TrackYourFlight.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ForecastDataContext : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ForecastDataContext));
        
        string IMigrationMetadata.Id
        {
            get { return "201706071523179_ForecastDataContext"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
